version: '2'
services:
    cvgenerator-app:
        image: cvgenerator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cvgenerator-mysql:3306/cvgenerator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cvgenerator-mysql:
        extends:
            file: mysql.yml
            service: cvgenerator-mysql
